"""Competitor data

Revision ID: 22f998185cca
Revises: 6e0e0503902f
Create Date: 2021-02-28 00:04:50.717449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f998185cca'
down_revision = '6e0e0503902f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor', sa.Column('birthday_date', sa.Date(), nullable=True))
    op.add_column('competitor', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('competitor', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitor', 'weight')
    op.drop_column('competitor', 'height')
    op.drop_column('competitor', 'birthday_date')
    # ### end Alembic commands ###
