"""Move position from tables

Revision ID: 23483b5ed27e
Revises: 69f67c5479fc
Create Date: 2021-03-06 15:21:25.522345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23483b5ed27e'
down_revision = '69f67c5479fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('position', sa.Integer(), nullable=True))
    op.drop_column('link_competition_category', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_competition_category', sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('category', 'position')
    # ### end Alembic commands ###
