"""Add not null to competition_id in team

Revision ID: 3555e0216480
Revises: 7a3246e50bcd
Create Date: 2021-06-06 15:21:34.287121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3555e0216480'
down_revision = '7a3246e50bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'competition_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team', 'competition_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
