"""Add is_amrap to event

Revision ID: 6406b7c8b95b
Revises: d1f14f480012
Create Date: 2021-03-13 13:55:06.433036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6406b7c8b95b'
down_revision = 'd1f14f480012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('is_amrap', sa.Boolean(), server_default=sa.text('True'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'is_amrap')
    # ### end Alembic commands ###
