"""Add position to LinkCompetitionCategory

Revision ID: 69f67c5479fc
Revises: 9737b5d21483
Create Date: 2021-03-06 14:56:38.640430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69f67c5479fc'
down_revision = '9737b5d21483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_competition_category', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_competition_category', 'position')
    # ### end Alembic commands ###
