"""Add country

Revision ID: 6e0e0503902f
Revises: b13547730cc0
Create Date: 2021-02-23 22:01:03.373298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e0e0503902f'
down_revision = 'b13547730cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('country',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gender',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('competitor', sa.Column('gender_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('competitor', sa.Column('nationality_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'competitor', 'gender', ['gender_id'], ['id'])
    op.create_foreign_key(None, 'competitor', 'country', ['nationality_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'competitor', type_='foreignkey')
    op.drop_constraint(None, 'competitor', type_='foreignkey')
    op.drop_column('competitor', 'nationality_id')
    op.drop_column('competitor', 'gender_id')
    op.drop_table('gender')
    op.drop_table('country')
    op.drop_table('competition')
    # ### end Alembic commands ###
