"""Add anonymous to competitor

Revision ID: 77e078c295df
Revises: 7d2fe24f6b7c
Create Date: 2021-06-05 17:47:38.604916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e078c295df'
down_revision = '7d2fe24f6b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor', sa.Column('anonymous', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitor', 'anonymous')
    # ### end Alembic commands ###
