"""Add link team competition

Revision ID: 7d2fe24f6b7c
Revises: a8a6e209442c
Create Date: 2021-06-05 17:31:31.714638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d2fe24f6b7c'
down_revision = 'a8a6e209442c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_competition_team',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('team_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('competition_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_competition_team')
    # ### end Alembic commands ###
