"""Add is_team to category

Revision ID: 860b59a421bf
Revises: 3555e0216480
Create Date: 2021-06-06 15:48:54.731056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860b59a421bf'
down_revision = '3555e0216480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_team', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'is_team')
    # ### end Alembic commands ###
