"""add unique on team/event

Revision ID: 8fa8964e4712
Revises: 860b59a421bf
Create Date: 2021-06-17 18:40:02.548428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa8964e4712'
down_revision = '860b59a421bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'score', ['team_id', 'event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score', type_='unique')
    # ### end Alembic commands ###
