"""Add team to score

Revision ID: a8a6e209442c
Revises: 1b0a1f12bd16
Create Date: 2021-05-29 20:30:48.833646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8a6e209442c'
down_revision = '1b0a1f12bd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('team_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'score', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.drop_column('score', 'team_id')
    # ### end Alembic commands ###
