"""Add avatar to competitor

Revision ID: aa87c6e976d5
Revises: 6c6e461f8d6c
Create Date: 2021-03-01 19:34:14.555283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa87c6e976d5'
down_revision = '6c6e461f8d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor', sa.Column('avatar', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitor', 'avatar')
    # ### end Alembic commands ###
