"""country iso

Revision ID: abf0b7c5ba1f
Revises: 22f998185cca
Create Date: 2021-02-28 11:01:53.704687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf0b7c5ba1f'
down_revision = '22f998185cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('iso2', sa.Text(), nullable=False))
    op.add_column('country', sa.Column('iso3', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'iso3')
    op.drop_column('country', 'iso2')
    # ### end Alembic commands ###
