"""Add tiebreak to event

Revision ID: b293b61043ae
Revises: 78b0f7db77fb
Create Date: 2021-03-11 18:19:59.501123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b293b61043ae'
down_revision = '78b0f7db77fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('has_tiebreak', sa.Boolean(), server_default=sa.text('False'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'has_tiebreak')
    # ### end Alembic commands ###
