"""Add competitor to score

Revision ID: c4fccef38192
Revises: ee73c42adcaa
Create Date: 2021-03-03 18:33:23.879546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4fccef38192'
down_revision = 'ee73c42adcaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('competitor_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'score', 'competitor', ['competitor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score', type_='foreignkey')
    op.drop_column('score', 'competitor_id')
    # ### end Alembic commands ###
