"""Add tiebreak to event

Revision ID: d1f14f480012
Revises: b293b61043ae
Create Date: 2021-03-11 19:25:11.224011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f14f480012'
down_revision = 'b293b61043ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('time_cap', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('tiebreak', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'time')
    op.drop_column('score', 'tiebreak')
    op.drop_column('event', 'time_cap')
    # ### end Alembic commands ###
