"""Add link competition/competitors

Revision ID: d97af6673303
Revises: db6514bc0e7e
Create Date: 2021-03-04 20:40:34.120533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd97af6673303'
down_revision = 'db6514bc0e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_competition_competitor',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('competitor_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('competition_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link_competition_competitor')
    # ### end Alembic commands ###
