"""Add to event if max rep is best score

Revision ID: e745c8f6a08d
Revises: 23483b5ed27e
Create Date: 2021-03-06 15:48:06.339113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e745c8f6a08d'
down_revision = '23483b5ed27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('max_score_best', sa.Boolean(), server_default=sa.text('True'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'max_score_best')
    # ### end Alembic commands ###
